from django.contrib import admin
from main.models import *
# Register your models here.
admin.site.register(Catalog)
admin.site.register(Category)
admin.site.register(CategoryType)
admin.site.register(CategorySize)
admin.site.register(Size)
admin.site.register(Color)
admin.site.register(Product)
admin.site.register(Service)
admin.site.register(BlogCategory)
admin.site.register(Blog)
admin.site.register(BlogQoute)
admin.site.register(Sponsor)
admin.site.register(Main)
admin.site.register(About)
admin.site.register(Comment)
admin.site.register(Statistics)
admin.site.register(Staff)
admin.site.register(Contact)
admin.site.register(Register)
