# Generated by Django 4.0.4 on 2022-06-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kaspi_link',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
