# Generated by Django 4.0.4 on 2022-06-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_kaspi_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pr_amount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
