# Generated by Django 4.0.4 on 2022-06-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_pr_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='col_amount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
