# Generated by Django 4.0.4 on 2022-06-20 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_categorysize_pr_amount_categorytype_pr_amount'),
        ('main', '0006_main'),
    ]

    operations = [
    ]
